In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
a = np.array([1.45, 4, 2, 3])

In [4]:
print(a)

[1.45 4.   2.   3.  ]


In [5]:
type(a)

numpy.ndarray

In [6]:
np.array([1, 2, 3, 4, 5], dtype=float)

array([1., 2., 3., 4., 5.])

In [7]:
np.array([range(i, i + 5) for i in [2, 4, 6]])

array([[ 2,  3,  4,  5,  6],
       [ 4,  5,  6,  7,  8],
       [ 6,  7,  8,  9, 10]])

In [8]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [9]:
#length-8 integer array filled with zeros
np.zeros(8, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
#3x5 floating-point array filled with ones
np.ones((4, 6), dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [11]:
#3x5 array filled with 22
np.full((5, 5), 32)

array([[32, 32, 32, 32, 32],
       [32, 32, 32, 32, 32],
       [32, 32, 32, 32, 32],
       [32, 32, 32, 32, 32],
       [32, 32, 32, 32, 32]])

In [12]:
#array starting with 0, ending at 30 and step size is 3
np.arange(0, 63, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60])

In [13]:
#3x3 array with random values between 0 and 1
np.random.random((4, 4))

array([[0.48196002, 0.62577004, 0.22295199, 0.51795635],
       [0.98832131, 0.32496683, 0.37845131, 0.19596977],
       [0.21943332, 0.45457047, 0.50805032, 0.59487046],
       [0.90140492, 0.75261275, 0.64778839, 0.64580683]])

In [14]:
#3x3 identity matrix
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [15]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [16]:
print(x3.ndim)
print(x3.shape)
print(x3.size)

3
(3, 4, 5)
60


In [17]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [18]:
x1

array([5, 0, 3, 3, 7, 9])

In [19]:
x1[0]

5

In [20]:
x1[4]

7

In [21]:
x1[-1]

9

In [22]:
x1[-2]

7

In [23]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [24]:
x2[0, 0]

3

In [25]:
x2[2, 0]

1

In [26]:
x2[2, -1]

7

In [27]:
x2[0, 0] = 10
x2

array([[10,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [28]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

In [29]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [31]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [32]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [33]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [34]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [35]:
x2

array([[10,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [36]:
x2[:2, :3]  # two rows, three columns

array([[10,  5,  2],
       [ 7,  6,  8]])

In [37]:
x2[:3, ::2]  # all rows, every other column

array([[10,  2],
       [ 7,  8],
       [ 1,  7]])

In [38]:
print(x2[:, 0])  # first column of x2

[10  7  1]


In [39]:
print(x2[0, :])  # first row of x2

[10  5  2  4]


In [40]:
print(x2[0])  # equivalent to x2[0, :]

[10  5  2  4]


In [41]:
x = np.arange(1, 17)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [42]:
x.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [43]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [44]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [45]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [46]:
z = [99, 99, 99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [47]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])

In [48]:
# concatenate along the first axis
np.concatenate([x, x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [49]:
# concatenate along the second axis (zero-indexed)
np.concatenate([x, x], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [50]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [4, 5])
print(x1, x2, x3)

[ 1  2  3 99] [99] [3 2 1]


In [51]:
x = np.arange(16).reshape((4, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
upper, lower = np.vsplit(x, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [53]:
left, right = np.hsplit(x, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [54]:
x = np.arange(4)

In [55]:
x

array([0, 1, 2, 3])

In [56]:
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x //2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x //2 = [0 0 1 1]


In [57]:
print("-x     = ", -x)
print("x ** 3 = ", x ** 3)
print("x % 3  = ", x % 3)

-x     =  [ 0 -1 -2 -3]
x ** 3 =  [ 0  1  8 27]
x % 3  =  [0 1 2 0]


In [58]:
x

array([0, 1, 2, 3])

In [59]:
np.add(x, 2)

array([2, 3, 4, 5])

In [60]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [61]:
L = np.random.random(100)
sum(L)

52.12818058833704

In [62]:
np.sum(L)

52.12818058833702

In [63]:
big_array = np.random.rand(1000000)

In [64]:
min(big_array), max(big_array)

(1.4057692298008462e-06, 0.9999994392723005)

In [65]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])